#+title: Numeric table

* Aim

  Collection of tabular data structures for use in statistics and
  numerical data analysis.  The structure supports table queries and
  selections.  In addition, numerical analysis (such as fitting,
  interpolation) can be performed on columns, rows or regions.


  The query and selection functionality replicates and expand
  functionality provided by Chapter 27 of "Practical Common Lisp".
  The difference between this code and PCL's code is that our code is
  more geared towards numerical data, while PCL is more data-base like.
  type of app.

* Supported data formats

  Currently there is only one supported format: [[*COLUMN-MAJOR-TABLE][COLUMN-MAJOR-TABLE]]


** COLUMN-MAJOR-TABLE

   Stores data that is organized by columns, each column having a name
   and storing values of a one type.  The data in columns can be
   stored as foreign arrays and used in numerical analysis via GSLL.

   For examples of use of column-major-tables see [[file:user/example1/README.org][this file]], and
   other lisp and png files in that directory.

   I am currently investigating the following use of numeric table:
   - numeric table as a data frame to hold multiple columns of data
   - A recursive structure of data frame to hold multiple data
     frames, all related by a common thread
   - data frames and recursive data frames as a basic data structure
     for the grammar of graphics
   - These topics are discussed in [[file:doc/data-frames%2Bgog.org][this document]].


*** Initialization of a column-major-table

    The table contents can be specified in three manners:
    - ~add-row~, row-by-row method
    - ~set-column~, set-column method
    - ~add-column~ *not implemented*
    - ~set-value~, any

      
    The table can be initialized as follows
    #+BEGIN_SRC lisp
      (make-table 'column-major-table schema)
      (make-table 'column-major-table schema row-count)
    #+END_SRC
    The first method initializes the table so that ~add-row~ and
    ~set-column~ are operational.  In the first method, internally,
    spine is initialized with empty adjustable vectors.  These are
    extended as rows are added setting the mode to row-by-row, or
    overwritten by columns, setting the mode to set-column.

    The second method initializes the table so that ~set-column~ and
    ~set-value~ are operational.  Internally, the storage is
    initialized to a series of empty column vectors.  ~set-value~ can
    operate on them.

    The table cannot be created pre-loaded with data.  This effect
    can be achieved by a user function or macro that creates a new
    table and then inserts contents into it.

**** Internal operation
     
* Documentation

  Documentation is maintained for users and separately for
  developers/maintainers.  The documentation sources are in the ~doc~
  directory.  The html files are in the ~documentation~ directory.
  The documentation is not yet complete.

* Architecture

  I see this library supporting several types of table formats.  They
  will be unified by a uniform interface (as much as possible).  To
  that end, there is a section of the library that deals with base
  class and generic function definitions.

  These are then specialized for various table types.

  Currently, I support only one table type, ~column-major-table~.  The
  data is stored as nested vectors.  Top level vector holds the
  columns.  Each column is stored in a vector.  The vectors can be
  either native CL or ~grid~'s foreign-array.

* Note

  This library may become part of the data-frame capability of the
  [[https://groups.google.com/forum/?hl%3Den&fromgroups#!forum/lisp-stat][Common Lisp Statistics]] library.

  
